### ISSUE TITLE
Improve appearance of full-screen images on the right side

### ISSUE THREAD

**Issue by chetjasinski** [superlou/zenkaikon24#20]
This is the diagonal line that splits the 1/3 and 2/3 sections.  It's more of the visual aesthetic due to the map.

**Comment by superlou** [comment]
If the diagonal line looked professional, with the map or other image taking up the full (cropped by the diagonal) right area, would we want to leave it?

Aside: I'm a little nervous about maps, because they take up a lot of rotation time but are still too fast for someone to really get their bearings. They also don't change often, so are better served by large format prints. Keeping the currently running and up next shows cycling as often as possible was a big reason we pulled the "all day" events to the left panel.

**Comment by chetjasinski** [comment]
Only 1 map will be associated with the floor that the digital sign is on via MAC address/Info-beamer Set-Up.   There will not be a rotation through all the maps.  Bert did it that way so that I could see all the maps.

**Comment by superlou** [comment]
> Only 1 map will be associated with the floor that the digital sign is on via MAC address/Info-beamer Set-Up. There will not be a rotation through all the maps. Bert did it that way so that I could see all the maps.

Ah, that fixes my concern, thanks! So, can we leave the slash if I can make it look professional?

**Comment by chetjasinski** [comment]
Sure!   If you can "make it work" by all means.

**Comment by superlou** [comment]
@chetjasinski, try it now. On the Pi 3, it's a little slow, but it should be fast enough on your 4. I need to go back and forth between the two. For reference, [this thread](https://community.info-beamer.com/t/masking-an-image-to-a-non-rectangular-shape/1274/3) covers the technique used.

**Comment by superlou** [comment]
This is working, though it's slow on the RPi 3.
